version: "3.1"
services:

  phpmyadmin:
    container_name: test_currency_exchange_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: user
      PMA_PASSWORD: password
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    restart: always
    ports:
      - 8081:80
    depends_on:
       - database
    networks:
      - app-network

  database:
    image: mysql:5.7
    restart: unless-stopped
    container_name: test_currency_exchange_mysql
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - './docker/mysql:/etc/mysql'
      - 'mysql_data:/var/lib/mysql'
    ports:
      - '3307:3306'
    networks:
      - app-network
  php:
    build: ./docker/php
    restart: unless-stopped
    container_name: test_currency_exchange_php
    working_dir: /app
    volumes:
      - ./api:/app
      - ./docker/php/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    ports:
      - "8080:5200"
    networks:
      - app-network
    depends_on:
      - database

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
